export const countries = [
  {
    name: 'Afghanistan',
    code: 'AF',
    dialCode: '+93',
    flag: 'assets/flags/af.png',
  },
  {
    name: 'Albania',
    code: 'AL',
    dialCode: '+355',
    flag: 'assets/flags/al.png',
  },
  {
    name: 'Algeria',
    code: 'DZ',
    dialCode: '+213',
    flag: 'assets/flags/dz.png',
  },
  {
    name: 'Andorra',
    code: 'AD',
    dialCode: '+376',
    flag: 'assets/flags/ad.png',
  },
  {
    name: 'Angola',
    code: 'AO',
    dialCode: '+244',
    flag: 'assets/flags/ao.png',
  },
  {
    name: 'Antigua and Barbuda',
    code: 'AG',
    dialCode: '+1268',
    flag: 'assets/flags/ag.png',
  },
  {
    name: 'Argentina',
    code: 'AR',
    dialCode: '+54',
    flag: 'assets/flags/ar.png',
  },
  {
    name: 'Armenia',
    code: 'AM',
    dialCode: '+374',
    flag: 'assets/flags/am.png',
  },
  {
    name: 'Australia',
    code: 'AU',
    dialCode: '+61',
    flag: 'assets/flags/au.png',
  },
  {
    name: 'Austria',
    code: 'AT',
    dialCode: '+43',
    flag: 'assets/flags/at.png',
  },
  {
    name: 'Azerbaijan',
    code: 'AZ',
    dialCode: '+994',
    flag: 'assets/flags/az.png',
  },
  {
    name: 'Bahamas, The',
    code: 'BS',
    dialCode: '+1242',
    flag: 'assets/flags/bs.png',
  },
  {
    name: 'Bahrain',
    code: 'BH',
    dialCode: '+973',
    flag: 'assets/flags/bh.png',
  },
  {
    name: 'Bangladesh',
    code: 'BD',
    dialCode: '+880',
    flag: 'assets/flags/bd.png',
  },
  {
    name: 'Barbados',
    code: 'BB',
    dialCode: '+1',
    flag: 'assets/flags/bb.png',
  },
  {
    name: 'Belarus',
    code: 'BY',
    dialCode: '+375',
    flag: 'assets/flags/by.png',
  },
  {
    name: 'Belgium',
    code: 'BE',
    dialCode: '+32',
    flag: 'assets/flags/be.png',
  },
  {
    name: 'Belize',
    code: 'BZ',
    dialCode: '+501',
    flag: 'assets/flags/bz.png',
  },
  {
    name: 'Benin (Dahomey)',
    code: 'BJ',
    dialCode: '+229',
    flag: 'assets/flags/bj.png',
  },
  {
    name: 'Bolivia',
    code: 'BO',
    dialCode: '+591',
    flag: 'assets/flags/bo.png',
  },
  {
    name: 'Bosnia and Herzegovina',
    code: 'BA',
    dialCode: '+387',
    flag: 'assets/flags/ba.png',
  },
  {
    name: 'Botswana',
    code: 'BW',
    dialCode: '+267',
    flag: 'assets/flags/bw.png',
  },
  {
    name: 'Brazil',
    code: 'BR',
    dialCode: '+55',
    flag: 'assets/flags/br.png',
  },
  {
    name: 'Brunei',
    code: 'BN',
    dialCode: '+673',
    flag: 'assets/flags/bn.png',
  },
  {
    name: 'Bulgaria',
    code: 'BG',
    dialCode: '+359',
    flag: 'assets/flags/bg.png',
  },
  {
    name: 'Burkina Faso (Upper Volta)',
    code: 'BF',
    dialCode: '+226',
    flag: 'assets/flags/bf.png',
  },
  {
    name: 'Burma',
    code: 'MM',
    dialCode: '+95',
    flag: 'assets/flags/mm.png',
  },
  {
    name: 'Burundi',
    code: 'BI',
    dialCode: '+257',
    flag: 'assets/flags/bi.png',
  },
  {
    name: 'Cabo Verde',
    code: 'CV',
    dialCode: '+238',
    flag: 'assets/flags/cv.png',
  },
  {
    name: 'Cambodia',
    code: 'KH',
    dialCode: '+855',
    flag: 'assets/flags/kh.png',
  },
  {
    name: 'Cameroon',
    code: 'CM',
    dialCode: '+237',
    flag: 'assets/flags/cm.png',
  },
  {
    name: 'Canada',
    code: 'CA',
    dialCode: '+1',
    flag: 'assets/flags/ca.png',
  },
  {
    name: 'Cayman Islands, The',
    code: 'KY',
    dialCode: '+1345',
    flag: 'assets/flags/ky.png',
  },
  {
    name: 'Central African Republic',
    code: 'CF',
    dialCode: '+236',
    flag: 'assets/flags/cf.png',
  },
  {
    name: 'Chad',
    code: 'TD',
    dialCode: '+235',
    flag: 'assets/flags/td.png',
  },
  {
    name: 'Chile',
    code: 'CL',
    dialCode: '+56',
    flag: 'assets/flags/cl.png',
  },
  {
    name: 'China',
    code: 'CN',
    dialCode: '+86',
    flag: 'assets/flags/cn.png',
  },
  {
    name: 'Colombia',
    code: 'CO',
    dialCode: '+57',
    flag: 'assets/flags/co.png',
  },
  {
    name: 'Comoros',
    code: 'KM',
    dialCode: '+269',
    flag: 'assets/flags/km.png',
  },
  {
    name: 'Cook Islands',
    code: 'CK',
    dialCode: '+682',
    flag: 'assets/flags/ck.png',
  },
  {
    name: 'Costa Rica',
    code: 'CR',
    dialCode: '+506',
    flag: 'assets/flags/cr.png',
  },
  {
    name: 'Cote d’Ivoire (Ivory Coast)',
    code: 'CI',
    dialCode: '+225',
    flag: 'assets/flags/ci.png',
  },
  {
    name: 'Croatia',
    code: 'HR',
    dialCode: '+385',
    flag: 'assets/flags/hr.png',
  },
  {
    name: 'Cuba',
    code: 'CU',
    dialCode: '+53',
    flag: 'assets/flags/cu.png',
  },
  {
    name: 'Cyprus',
    code: 'CY',
    dialCode: '+357',
    flag: 'assets/flags/cy.png',
  },
  {
    name: 'Czechia',
    code: 'CZ',
    dialCode: '+420',
    flag: 'assets/flags/cz.png',
  },
  {
    name: 'Democratic Republic of the Congo',
    code: 'CD',
    dialCode: '+243',
    flag: 'assets/flags/cd.png',
  },
  {
    name: 'Denmark',
    code: 'DK',
    dialCode: '+45',
    flag: 'assets/flags/dk.png',
  },
  {
    name: 'Djibouti',
    code: 'DJ',
    dialCode: '+253',
    flag: 'assets/flags/dj.png',
  },
  {
    name: 'Dominica',
    code: 'DM',
    dialCode: '+1767',
    flag: 'assets/flags/dm.png',
  },
  {
    name: 'Dominican Republic',
    code: 'DO',
    dialCode: '+1',
    flag: 'assets/flags/do.png',
  },
  {
    name: 'Ecuador',
    code: 'EC',
    dialCode: '+593',
    flag: 'assets/flags/ec.png',
  },
  {
    name: 'Egypt',
    code: 'EG',
    dialCode: '+20',
    flag: 'assets/flags/eg.png',
  },
  {
    name: 'El Salvador',
    code: 'SV',
    dialCode: '+503',
    flag: 'assets/flags/sv.png',
  },
  {
    name: 'Equatorial Guinea',
    code: 'GQ',
    dialCode: '+240',
    flag: 'assets/flags/gq.png',
  },
  {
    name: 'Eritrea',
    code: 'ER',
    dialCode: '+291',
    flag: 'assets/flags/er.png',
  },
  {
    name: 'Estonia',
    code: 'EE',
    dialCode: '+372',
    flag: 'assets/flags/ee.png',
  },
  {
    name: 'Eswatini',
    code: 'SZ',
    dialCode: '+268',
    flag: 'assets/flags/sz.png',
  },
  {
    name: 'Ethiopia',
    code: 'ET',
    dialCode: '+251',
    flag: 'assets/flags/et.png',
  },
  {
    name: 'Fiji',
    code: 'FJ',
    dialCode: '+679',
    flag: 'assets/flags/fj.png',
  },
  {
    name: 'Finland',
    code: 'FI',
    dialCode: '+358',
    flag: 'assets/flags/fi.png',
  },
  {
    name: 'France',
    code: 'FR',
    dialCode: '+33',
    flag: 'assets/flags/fr.png',
  },
  {
    name: 'Gabon',
    code: 'GA',
    dialCode: '+241',
    flag: 'assets/flags/ga.png',
  },
  {
    name: 'Gambia, The',
    code: 'GM',
    dialCode: '+220',
    flag: 'assets/flags/gm.png',
  },
  {
    name: 'Georgia',
    code: 'GE',
    dialCode: '+995',
    flag: 'assets/flags/ge.png',
  },
  {
    name: 'Germany',
    code: 'DE',
    dialCode: '+49',
    flag: 'assets/flags/de.png',
  },
  {
    name: 'Ghana',
    code: 'GH',
    dialCode: '+233',
    flag: 'assets/flags/gh.png',
  },
  {
    name: 'Greece',
    code: 'GR',
    dialCode: '+30',
    flag: 'assets/flags/gr.png',
  },
  {
    name: 'Grenada',
    code: 'GD',
    dialCode: '+1473',
    flag: 'assets/flags/gd.png',
  },
  {
    name: 'Guatemala',
    code: 'GT',
    dialCode: '+502',
    flag: 'assets/flags/gt.png',
  },
  {
    name: 'Guinea',
    code: 'GN',
    dialCode: '+224',
    flag: 'assets/flags/gn.png',
  },
  {
    name: 'Guinea-Bissau',
    code: 'GW',
    dialCode: '+245',
    flag: 'assets/flags/gw.png',
  },
  {
    name: 'Guyana',
    code: 'GY',
    dialCode: '+592',
    flag: 'assets/flags/gy.png',
  },
  {
    name: 'Haiti',
    code: 'HT',
    dialCode: '+509',
    flag: 'assets/flags/ht.png',
  },
  {
    name: 'Holy See',
    code: 'VA',
    dialCode: '+39',
    flag: 'assets/flags/va.png',
  },
  {
    name: 'Honduras',
    code: 'HN',
    dialCode: '+504',
    flag: 'assets/flags/hn.png',
  },
  {
    name: 'Hungary',
    code: 'HU',
    dialCode: '+36',
    flag: 'assets/flags/hu.png',
  },
  {
    name: 'Iceland',
    code: 'IS',
    dialCode: '+354',
    flag: 'assets/flags/is.png',
  },
  {
    name: 'India',
    code: 'IN',
    dialCode: '+91',
    flag: 'assets/flags/in.png',
  },
  {
    name: 'Indonesia',
    code: 'ID',
    dialCode: '+62',
    flag: 'assets/flags/id.png',
  },
  {
    name: 'Iran',
    code: 'IR',
    dialCode: '+98',
    flag: 'assets/flags/ir.png',
  },
  {
    name: 'Iraq',
    code: 'IQ',
    dialCode: '+964',
    flag: 'assets/flags/iq.png',
  },
  {
    name: 'Ireland',
    code: 'IE',
    dialCode: '+353',
    flag: 'assets/flags/ie.png',
  },
  {
    name: 'Israel',
    code: 'IL',
    dialCode: '+972',
    flag: 'assets/flags/il.png',
  },
  {
    name: 'Italy',
    code: 'IT',
    dialCode: '+39',
    flag: 'assets/flags/it.png',
  },
  {
    name: 'Jamaica',
    code: 'JM',
    dialCode: '+1',
    flag: 'assets/flags/jm.png',
  },
  {
    name: 'Japan',
    code: 'JP',
    dialCode: '+81',
    flag: 'assets/flags/jp.png',
  },
  {
    name: 'Jordan',
    code: 'JO',
    dialCode: '+962',
    flag: 'assets/flags/jo.png',
  },
  {
    name: 'Kazakhstan',
    code: 'KZ',
    dialCode: '+7',
    flag: 'assets/flags/kz.png',
  },
  {
    name: 'Kenya',
    code: 'KE',
    dialCode: '+254',
    flag: 'assets/flags/ke.png',
  },
  {
    name: 'Kiribati',
    code: 'KI',
    dialCode: '+686',
    flag: 'assets/flags/ki.png',
  },
  {
    name: 'Kosovo',
    code: 'XK',
    dialCode: '+383',
    flag: 'assets/flags/xk.png',
  },
  {
    name: 'Kuwait',
    code: 'KW',
    dialCode: '+965',
    flag: 'assets/flags/kw.png',
  },
  {
    name: 'Kyrgyzstan',
    code: 'KG',
    dialCode: '+996',
    flag: 'assets/flags/kg.png',
  },
  {
    name: 'Laos',
    code: 'LA',
    dialCode: '+856',
    flag: 'assets/flags/la.png',
  },
  {
    name: 'Latvia',
    code: 'LV',
    dialCode: '+371',
    flag: 'assets/flags/lv.png',
  },
  {
    name: 'Lebanon',
    code: 'LB',
    dialCode: '+961',
    flag: 'assets/flags/lb.png',
  },
  {
    name: 'Lesotho',
    code: 'LS',
    dialCode: '+266',
    flag: 'assets/flags/ls.png',
  },
  {
    name: 'Liberia',
    code: 'LR',
    dialCode: '+231',
    flag: 'assets/flags/lr.png',
  },
  {
    name: 'Libya',
    code: 'LY',
    dialCode: '+218',
    flag: 'assets/flags/ly.png',
  },
  {
    name: 'Liechtenstein',
    code: 'LI',
    dialCode: '+423',
    flag: 'assets/flags/li.png',
  },
  {
    name: 'Lithuania',
    code: 'LT',
    dialCode: '+370',
    flag: 'assets/flags/lt.png',
  },
  {
    name: 'Luxembourg',
    code: 'LU',
    dialCode: '+352',
    flag: 'assets/flags/lu.png',
  },
  {
    name: 'Madagascar',
    code: 'MG',
    dialCode: '+261',
    flag: 'assets/flags/mg.png',
  },
  {
    name: 'Malawi',
    code: 'MW',
    dialCode: '+265',
    flag: 'assets/flags/mw.png',
  },
  {
    name: 'Malaysia',
    code: 'MY',
    dialCode: '+60',
    flag: 'assets/flags/my.png',
  },
  {
    name: 'Maldives',
    code: 'MV',
    dialCode: '+960',
    flag: 'assets/flags/mv.png',
  },
  {
    name: 'Mali',
    code: 'ML',
    dialCode: '+223',
    flag: 'assets/flags/ml.png',
  },
  {
    name: 'Malta',
    code: 'MT',
    dialCode: '+356',
    flag: 'assets/flags/mt.png',
  },
  {
    name: 'Marshall Islands',
    code: 'MH',
    dialCode: '+692',
    flag: 'assets/flags/mh.png',
  },
  {
    name: 'Mauritania',
    code: 'MR',
    dialCode: '+222',
    flag: 'assets/flags/mr.png',
  },
  {
    name: 'Mauritius',
    code: 'MU',
    dialCode: '+230',
    flag: 'assets/flags/mu.png',
  },
  {
    name: 'Mexico',
    code: 'MX',
    dialCode: '+52',
    flag: 'assets/flags/mx.png',
  },
  {
    name: 'Micronesia',
    code: 'FM',
    dialCode: '+691',
    flag: 'assets/flags/fm.png',
  },
  {
    name: 'Moldova',
    code: 'MD',
    dialCode: '+373',
    flag: 'assets/flags/md.png',
  },
  {
    name: 'Monaco',
    code: 'MC',
    dialCode: '+377',
    flag: 'assets/flags/mc.png',
  },
  {
    name: 'Mongolia',
    code: 'MN',
    dialCode: '+976',
    flag: 'assets/flags/mn.png',
  },
  {
    name: 'Montenegro',
    code: 'ME',
    dialCode: '+382',
    flag: 'assets/flags/me.png',
  },
  {
    name: 'Morocco',
    code: 'MA',
    dialCode: '+212',
    flag: 'assets/flags/ma.png',
  },
  {
    name: 'Mozambique',
    code: 'MZ',
    dialCode: '+258',
    flag: 'assets/flags/mz.png',
  },
  {
    name: 'Namibia',
    code: 'NA',
    dialCode: '+264',
    flag: 'assets/flags/na.png',
  },
  {
    name: 'Nauru',
    code: 'NR',
    dialCode: '+674',
    flag: 'assets/flags/nr.png',
  },
  {
    name: 'Nepal',
    code: 'NP',
    dialCode: '+977',
    flag: 'assets/flags/np.png',
  },
  {
    name: 'Netherlands, The',
    code: 'NL',
    dialCode: '+31',
    flag: 'assets/flags/nl.png',
  },
  {
    name: 'New Zealand',
    code: 'NZ',
    dialCode: '+64',
    flag: 'assets/flags/nz.png',
  },
  {
    name: 'Nicaragua',
    code: 'NI',
    dialCode: '+505',
    flag: 'assets/flags/ni.png',
  },
  {
    name: 'Niger',
    code: 'NE',
    dialCode: '+227',
    flag: 'assets/flags/ne.png',
  },
  {
    name: 'Nigeria',
    code: 'NG',
    dialCode: '+234',
    flag: 'assets/flags/ng.png',
  },
  {
    name: 'Niue',
    code: 'NU',
    dialCode: '+683',
    flag: 'assets/flags/nu.png',
  },
  {
    name: 'North Macedonia',
    code: 'MK',
    dialCode: '+389',
    flag: 'assets/flags/mk.png',
  },
  {
    name: 'Norway',
    code: 'NO',
    dialCode: '+47',
    flag: 'assets/flags/no.png',
  },
  {
    name: 'Oman',
    code: 'OM',
    dialCode: '+968',
    flag: 'assets/flags/om.png',
  },
  {
    name: 'Pakistan',
    code: 'PK',
    dialCode: '+92',
    flag: 'assets/flags/pk.png',
  },
  {
    name: 'Palau',
    code: 'PW',
    dialCode: '+680',
    flag: 'assets/flags/pw.png',
  },
  {
    name: 'Panama',
    code: 'PA',
    dialCode: '+507',
    flag: 'assets/flags/pa.png',
  },
  {
    name: 'Papua New Guinea',
    code: 'PG',
    dialCode: '+675',
    flag: 'assets/flags/pg.png',
  },
  {
    name: 'Paraguay',
    code: 'PY',
    dialCode: '+595',
    flag: 'assets/flags/py.png',
  },
  {
    name: 'Peru',
    code: 'PE',
    dialCode: '+51',
    flag: 'assets/flags/pe.png',
  },
  {
    name: 'Philippines',
    code: 'PH',
    dialCode: '+63',
    flag: 'assets/flags/ph.png',
  },
  {
    name: 'Poland',
    code: 'PL',
    dialCode: '+48',
    flag: 'assets/flags/pl.png',
  },
  {
    name: 'Portugal',
    code: 'PT',
    dialCode: '+351',
    flag: 'assets/flags/pt.png',
  },
  {
    name: 'Qatar',
    code: 'QA',
    dialCode: '+974',
    flag: 'assets/flags/qa.png',
  },
  {
    name: 'Republic of Korea (South Korea)',
    code: 'KR',
    dialCode: '+82',
    flag: 'assets/flags/kr.png',
  },
  {
    name: 'Republic of the Congo',
    code: 'CG',
    dialCode: '+242',
    flag: 'assets/flags/cg.png',
  },
  {
    name: 'Romania',
    code: 'RO',
    dialCode: '+40',
    flag: 'assets/flags/ro.png',
  },
  {
    name: 'Russia',
    code: 'RU',
    dialCode: '+7',
    flag: 'assets/flags/ru.png',
  },
  {
    name: 'Rwanda',
    code: 'RW',
    dialCode: '+250',
    flag: 'assets/flags/rw.png',
  },
  {
    name: 'Saint Kitts and Nevis',
    code: 'KN',
    dialCode: '+1869',
    flag: 'assets/flags/kn.png',
  },
  {
    name: 'Saint Lucia',
    code: 'LC',
    dialCode: '+1758',
    flag: 'assets/flags/lc.png',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    code: 'VC',
    dialCode: '+1784',
    flag: 'assets/flags/vc.png',
  },
  {
    name: 'Samoa',
    code: 'WS',
    dialCode: '+685',
    flag: 'assets/flags/ws.png',
  },
  {
    name: 'San Marino',
    code: 'SM',
    dialCode: '+378',
    flag: 'assets/flags/sm.png',
  },
  {
    name: 'Sao Tome and Principe',
    code: 'ST',
    dialCode: '+239',
    flag: 'assets/flags/st.png',
  },
  {
    name: 'Saudi Arabia',
    code: 'SA',
    dialCode: '+966',
    flag: 'assets/flags/sa.png',
  },
  {
    name: 'Senegal',
    code: 'SN',
    dialCode: '+221',
    flag: 'assets/flags/sn.png',
  },
  {
    name: 'Serbia',
    code: 'RS',
    dialCode: '+381',
    flag: 'assets/flags/rs.png',
  },
  {
    name: 'Seychelles',
    code: 'SC',
    dialCode: '+248',
    flag: 'assets/flags/sc.png',
  },
  {
    name: 'Sierra Leone',
    code: 'SL',
    dialCode: '+232',
    flag: 'assets/flags/sl.png',
  },
  {
    name: 'Singapore',
    code: 'SG',
    dialCode: '+65',
    flag: 'assets/flags/sg.png',
  },
  {
    name: 'Slovakia',
    code: 'SK',
    dialCode: '+421',
    flag: 'assets/flags/sk.png',
  },
  {
    name: 'Slovenia',
    code: 'SI',
    dialCode: '+386',
    flag: 'assets/flags/si.png',
  },
  {
    name: 'Solomon Islands, The',
    code: 'SB',
    dialCode: '+677',
    flag: 'assets/flags/sb.png',
  },
  {
    name: 'Somalia',
    code: 'SO',
    dialCode: '+252',
    flag: 'assets/flags/so.png',
  },
  {
    name: 'South Africa',
    code: 'ZA',
    dialCode: '+27',
    flag: 'assets/flags/za.png',
  },
  {
    name: 'South Sudan',
    code: 'SS',
    dialCode: '+211',
    flag: 'assets/flags/ss.png',
  },
  {
    name: 'Spain',
    code: 'ES',
    dialCode: '+34',
    flag: 'assets/flags/es.png',
  },
  {
    name: 'Sri Lanka',
    code: 'LK',
    dialCode: '+94',
    flag: 'assets/flags/lk.png',
  },
  {
    name: 'Sudan',
    code: 'SD',
    dialCode: '+249',
    flag: 'assets/flags/sd.png',
  },
  {
    name: 'Suriname',
    code: 'SR',
    dialCode: '+597',
    flag: 'assets/flags/sr.png',
  },
  {
    name: 'Sweden',
    code: 'SE',
    dialCode: '+46',
    flag: 'assets/flags/se.png',
  },
  {
    name: 'Switzerland',
    code: 'CH',
    dialCode: '+41',
    flag: 'assets/flags/ch.png',
  },
  {
    name: 'Syria',
    code: 'SY',
    dialCode: '+963',
    flag: 'assets/flags/sy.png',
  },
  {
    name: 'Tajikistan',
    code: 'TJ',
    dialCode: '+992',
    flag: 'assets/flags/tj.png',
  },
  {
    name: 'Tanzania',
    code: 'TZ',
    dialCode: '+255',
    flag: 'assets/flags/tz.png',
  },
  {
    name: 'Thailand',
    code: 'TH',
    dialCode: '+66',
    flag: 'assets/flags/th.png',
  },
  {
    name: 'Timor-Leste',
    code: 'TL',
    dialCode: '+670',
    flag: 'assets/flags/tl.png',
  },
  {
    name: 'Togo',
    code: 'TG',
    dialCode: '+228',
    flag: 'assets/flags/tg.png',
  },
  {
    name: 'Tonga',
    code: 'TO',
    dialCode: '+676',
    flag: 'assets/flags/to.png',
  },
  {
    name: 'Trinidad and Tobago',
    code: 'TT',
    dialCode: '+1868',
    flag: 'assets/flags/tt.png',
  },
  {
    name: 'Tunisia',
    code: 'TN',
    dialCode: '+216',
    flag: 'assets/flags/tn.png',
  },
  {
    name: 'Turkey',
    code: 'TR',
    dialCode: '+90',
    flag: 'assets/flags/tr.png',
  },
  {
    name: 'Turkmenistan',
    code: 'TM',
    dialCode: '+993',
    flag: 'assets/flags/tm.png',
  },
  {
    name: 'Tuvalu',
    code: 'TV',
    dialCode: '+688',
    flag: 'assets/flags/tv.png',
  },
  {
    name: 'Uganda',
    code: 'UG',
    dialCode: '+256',
    flag: 'assets/flags/ug.png',
  },
  {
    name: 'Ukraine',
    code: 'UA',
    dialCode: '+380',
    flag: 'assets/flags/ua.png',
  },
  {
    name: 'United Arab Emirates, The',
    code: 'AE',
    dialCode: '+971',
    flag: 'assets/flags/ae.png',
  },
  {
    name: 'United Kingdom, The',
    code: 'GB',
    dialCode: '+44',
    flag: 'assets/flags/gb.png',
  },
  {
    name: 'United States',
    code: 'US',
    dialCode: '+1',
    flag: 'assets/flags/us.png',
  },
  {
    name: 'Uruguay',
    code: 'UY',
    dialCode: '+598',
    flag: 'assets/flags/uy.png',
  },
  {
    name: 'Uzbekistan',
    code: 'UZ',
    dialCode: '+998',
    flag: 'assets/flags/uz.png',
  },
  {
    name: 'Vanuatu',
    code: 'VU',
    dialCode: '+678',
    flag: 'assets/flags/vu.png',
  },
  {
    name: 'Venezuela',
    code: 'VE',
    dialCode: '+58',
    flag: 'assets/flags/ve.png',
  },
  {
    name: 'Vietnam',
    code: 'VN',
    dialCode: '+84',
    flag: 'assets/flags/vn.png',
  },
  {
    name: 'Yemen',
    code: 'YE',
    dialCode: '+967',
    flag: 'assets/flags/ye.png',
  },
  {
    name: 'Zambia',
    code: 'ZM',
    dialCode: '+260',
    flag: 'assets/flags/zm.png',
  },
  {
    name: 'Zimbabwe',
    code: 'ZW',
    dialCode: '+263',
    flag: 'assets/flags/zw.png',
  },
];